### ISSUE TITLE
Add season and episode info to file name when downloading

### ISSUE THREAD

**Issue by OneLoveAmaru** [jradwan/TiVoToGo.bundle#6]
I'd love to be able to download the TV shows and have Plex pick them up but since there is no season or episode in the filename or metadata, Plex just ignores them. TheTVDB.com has a free API and Plex uses them for the TV info already.

**Comment by jradwan** [comment]
From the [README](https://github.com/jradwan/TiVoToGo.bundle/blob/master/README.md):

"If you want the plugin to properly name your downloaded file (for Plex agent metadata lookups), enter your TiVo Online username and password in the appropriate fields (this is currently broken on Windows, so leave these fields empty (see issue #5))."

Once the file is named properly, the regular Plex agent will do the metadata lookup. Even if the files aren't properly named, they should still appear in Plex if you are indexing that file location. They just might show up under "Movies" instead of "TV Shows" (at least that's what I've seen).

**Comment by jradwan** [comment]
Username/password issue for TiVo Online. Closing.
